### PR TITLE
Wrap a bunch of stuff, get things working with new Julia!

### PR DESCRIPTION
**Pull request by kshyatt**
I was waiting for some other code to finish running today ... as you can see there's something funny about https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/api/comms.html#ncclcomminitrank, it seems to be hanging for me. I ran the tests on a 2-GPU node of Voltas (so, single processor controls multiple GPUs) and they all passed. The initialization of the library stuff is very out of date, but you'd probably be better at fixing that than I am.

### CODE REVIEW

**Comment by vchuravy** [comment]
We should definitely combine our forces https://github.com/vchuravy/NCCL.jl

**Comment by maleadt** [comment]
Cool stuff. At the risk of bloating the package, I guess this would be a good fit for CuArrays.jl? I'll have a look at running the NCCL headers through my header generator and updating initialization, and then we can combine the best pieces of this PR and Valentin's fork.

**Comment by vchuravy** [comment]
It might make sense to keep it separate since you do need to use MPI to make it useful properly

**Comment by maleadt** [comment]
OK, let's merge this, I'll move the repo to JuliaGPU (I only intended it to be here for as long as I was experimenting with NCCL, if other people are using it JuliaGPU is a better place) and do some clean-up + generate wrappers. Beyond that I won't have the time or need to work on this, so I'll make you both collaborator.

**Pull request merged**
